// RULING R4-2 (2026-09-04-winter-phase-04-mcp-toolsearch-subagents.md): the subagent/messaging/MCP-
// control half of Task 3's own seam contracts -- tools/seam-contracts-p4.test.ts owns the
// registry/deferral half (MCP registration, Tool Search); this file owns ChildHandle, the
// adapter/router seam, and the two control-subtype bridges (McpControlSeam, sdk_mcp_call).
//
// Lanes A-D: THIS FILE IS THE SEAM AUTHORITY -- keep it green; do not edit it. If your change makes
// one of these tests fail, your change is inconsistent with the seam contract this task pinned, not
// a reason to relax the assertion. (If the contract itself is genuinely wrong, that is a spine
// change -- raise it with the controller, do not edit this file from a lane worktree.)
//
// EDITED TWICE SINCE, both times on the controller's explicit instruction, and both times ADDITIVE:
// (1) fix round 1 exported `createFakeChildHandle` so engine.test.ts could drive a real runEngine
// against this exact fixture; (2) the Phase 4 fix wave moved that fixture to `subagents/
// test-fakes.ts` (KNOWN item 2 -- so the four other files that use it stop importing a TEST file)
// and added ONE test pinning that every `ChildEngineRunContext` field the wave introduced is
// optional. No pre-existing assertion has ever been relaxed or removed.
//
// (i) proves ChildHandle's own state-machine SHAPE against a hand-built fake (Lane C's real
// child-engine.ts must satisfy the identical outcomes for the identical inputs -- steer while
// running delivers, resume a terminal child resumes-and-delivers, stop terminates, result()
// resolves exactly once regardless of how many times or when it's called).
// (ii) proves the adapter/router seam semantics (MessagingRouterSeam) against the spine's own fake.
// (iii) is tools/seam-contracts-p4.test.ts's own charter (isLoadFirstBlocked, extended there).
// (iv) proves McpControlSeam + rpc/mcp-control.ts's own handlers round-trip for all four
// host->runtime MCP control subtypes (mcp_status reads McpServerStateSource directly -- it has no
// McpControlSeam method of its own, see mcp/control-seam.ts's own header for why).
// (v) proves the sdk_mcp_call CONTRACT both legs of the bridge agree on: the WinterMcpServerInstance
// shape (packages/sdk/src/options.ts) a host's `instance` must satisfy to be end-to-end callable --
// the host-side responder's own full behavioral suite (registration gating, error taxonomy, the
// null-decline elicitation deviation) lives in packages/sdk/src/query.test.ts, which this spine task
// also authored; this file's own contribution is the shared TYPE contract, provable from the runtime
// side without duplicating that suite.
import { describe, test, expect } from "bun:test";
import { isWinterMcpServerInstance, type WinterMcpServerInstance } from "@yanlinglabs/winter-agent-sdk";
import { createFakeChildHandle } from "./test-fakes.ts";
import { createChildEngineFactory } from "./child-engine.ts";
import type { ChildEngineRunContext } from "./child-handle.ts";
import { createFakeMessagingRouterSeam } from "@yanlinglabs/winter-agent-sdk/messaging";
import { createFakeMcpControlSeam } from "../mcp/control-seam.ts";
import { createFakeMcpServerStateSource } from "../mcp/state.ts";
import { handleMcpStatus, handleMcpReconnect, handleMcpToggle, handleMcpSetServers } from "../rpc/mcp-control.ts";

// --- (i) ChildHandle semantics against a fake -----------------------------------------------------

// Phase 4 fix wave (KNOWN item 2): the fixture itself now lives in `subagents/test-fakes.ts` -- a
// plain module (imported at the top of this file), so the four other test files that use it no
// longer import a TEST file, which under bun's runner runs that file's whole suite as an import
// side effect. THIS file goes on testing the identical fake; no test body or assertion below
// changed, and this file remains the place where the fixture and the contract it satisfies are
// proven together.

describe("(i) ChildHandle semantics against a fake (WS-10 §7/§9/§15)", () => {
  test("steer() while running delivers", async () => {
    const child = createFakeChildHandle();
    const outcome = await child.steer({} as never);
    expect(outcome.status).toBe("delivered");
  });

  test("resume() on a completed (terminal, addressable) child resumes-and-delivers, and the child is running again", async () => {
    const child = createFakeChildHandle();
    child.simulateCompletion("first answer");
    expect(child.status()).toBe("completed");
    const outcome = await child.resume({} as never);
    expect(outcome.status).toBe("resumed_and_delivered");
    expect(child.status()).toBe("running");
  });

  test("resume() on a STILL-RUNNING child is refused (resume targets a terminal child only)", async () => {
    const child = createFakeChildHandle();
    const outcome = await child.resume({} as never);
    expect(outcome.status).not.toBe("resumed_and_delivered");
  });

  test("stop() terminates the child and settles result() with a stopped outcome", async () => {
    const child = createFakeChildHandle();
    const resultPromise = child.result();
    await child.stop();
    expect(child.status()).toBe("stopped");
    expect(await resultPromise).toEqual({ status: "stopped", content: "stopped by request" });
  });

  test("result() resolves exactly once -- every caller (before or after completion) observes the SAME settled value", async () => {
    const child = createFakeChildHandle();
    const before1 = child.result();
    const before2 = child.result();
    child.simulateCompletion("done");
    const after = child.result();
    const [r1, r2, r3] = await Promise.all([before1, before2, after]);
    expect(r1).toEqual({ status: "completed", content: "done" });
    expect(r2).toEqual(r1);
    expect(r3).toEqual(r1);

    // A SECOND completion attempt (e.g. a duplicate signal) never re-settles or throws.
    child.simulateCompletion("a different answer -- must never overwrite the first");
    expect(await child.result()).toEqual(r1);
  });

  // Phase 4 fix wave: the wave added three fields to `ChildEngineRunContext` (parentAgentId,
  // getParentRules, getParentMcpState). Every one of them is OPTIONAL by contract -- a producer
  // that predates them (this file's own fakes; any host that builds a run context by hand) must
  // keep compiling AND keep working, degrading to the pre-wave behaviour rather than crashing.
  test("fix wave: every ChildEngineRunContext field added by the wave is OPTIONAL -- a context with only the two original members still builds real ChildEngineDeps", () => {
    const minimal: ChildEngineRunContext = { parentSessionId: "parent-1", forwardChildFrame: () => {} };
    expect(minimal.parentAgentId).toBeUndefined();
    expect(minimal.getParentRules).toBeUndefined();
    expect(minimal.getParentMcpState).toBeUndefined();
    expect(minimal.registerChildResponseHandler).toBeUndefined();
    expect(minimal.getParentPolicy).toBeUndefined();
    const deps = createChildEngineFactory({ provider: { async generate() { return { kind: "text", text: "unused" }; } } })(minimal);
    expect(typeof deps.spawn).toBe("function");
  });

  test("steer() after termination is refused, never silently delivered to a dead child", async () => {
    const child = createFakeChildHandle();
    child.simulateCompletion("done");
    const outcome = await child.steer({} as never);
    expect(outcome.status).not.toBe("delivered");
  });
});

// --- (ii) adapter/router seam semantics -------------------------------------------------------------

describe("(ii) MessagingRouterSeam semantics against the spine's own fake (WS-10 §12)", () => {
  test("allocateMessageId is allocated BEFORE resolution and is stable across a retry of the identical (senderSessionId, toolUseId) pair", () => {
    const seam = createFakeMessagingRouterSeam();
    const first = seam.allocateMessageId("s1", "tool-1");
    // A "retry" -- the identical sender+tool-call pair -- must return the SAME id, making
    // ambiguous/missing/unavailable outcomes idempotent too (WS-10 §12).
    const retry = seam.allocateMessageId("s1", "tool-1");
    expect(retry).toBe(first);
    expect(seam.lookupOutcome(first)).toBeUndefined(); // allocated, but nothing recorded yet -- resolution hasn't happened
  });

  test("recordOutcome / lookupOutcome round-trip and are idempotent (re-recording never throws, keeps the latest value)", () => {
    const seam = createFakeMessagingRouterSeam();
    const id = seam.allocateMessageId("s1", "tool-1");
    seam.recordOutcome(id, { status: "queued", messageId: id });
    expect(seam.lookupOutcome(id)).toEqual({ status: "queued", messageId: id });
    seam.recordOutcome(id, { status: "delivered", messageId: id });
    expect(seam.lookupOutcome(id)).toEqual({ status: "delivered", messageId: id });
  });

  test("children() reflects the live roster -- proven against the SAME fake ChildHandle (i) above builds", () => {
    const seam = createFakeMessagingRouterSeam();
    expect(seam.children()).toEqual([]);
    const child = createFakeChildHandle({ id: "child-2" });
    seam.setChildren([child]);
    expect(seam.children()).toEqual([child]);
    expect(seam.children()[0]?.record.id).toBe("child-2");
  });
});

// --- (iv) McpControlSeam fake round-trips for all four host->runtime MCP control subtypes -----------

describe("(iv) McpControlSeam + rpc/mcp-control.ts round-trips for all four host->runtime subtypes (WS-04 §3.1, WS-09 §2.1/§3)", () => {
  test("mcp_status reads McpServerStateSource.snapshot() directly (no McpControlSeam method -- see that seam's own header)", async () => {
    const stateSource = createFakeMcpServerStateSource([{ name: "gh", state: "needsAuth", toolNames: [] }]);
    const result = await handleMcpStatus({ stateSource });
    expect(result).toEqual({ ok: true, payload: { servers: [{ name: "gh", status: "needs-auth" }] } });
  });

  test("mcp_reconnect / mcp_toggle / mcp_set_servers round-trip through the fake McpControlSeam", async () => {
    const seam = createFakeMcpControlSeam();
    const deps = { controlSeam: seam };

    expect(await handleMcpReconnect(deps, { serverName: "gh" })).toEqual({ ok: true });
    expect(seam.calls.reconnect).toEqual(["gh"]);

    expect(await handleMcpToggle(deps, { serverName: "gh", enabled: false })).toEqual({ ok: true });
    expect(seam.calls.toggle).toEqual([{ serverName: "gh", enabled: false }]);

    seam.setServersResult = { added: ["new-srv"], removed: ["old-srv"], errors: {} };
    const setServersResult = await handleMcpSetServers(deps, { servers: { "new-srv": { command: "x" } } });
    expect(setServersResult).toEqual({ ok: true, payload: { added: ["new-srv"], removed: ["old-srv"], errors: {} } });
  });

  test("a seam rejection on any of the three mutating subtypes fails closed to a structured error, never a throw or a dropped request", async () => {
    const seam = createFakeMcpControlSeam();
    seam.failNextWith.reconnect = new Error("down");
    const result = await handleMcpReconnect({ controlSeam: seam }, { serverName: "gh" });
    expect(result).toEqual({ ok: false, error: { code: "mcp_reconnect_failed", message: "down" } });
  });
});

// --- (v) sdk_mcp_call: the shared type contract both legs of the bridge agree on --------------------

describe("(v) sdk_mcp_call host-responder contract: WinterMcpServerInstance (WS-04 addendum)", () => {
  test("isWinterMcpServerInstance requires BOTH listTools() and callTool() -- a partial shape is not callable", () => {
    expect(isWinterMcpServerInstance({ listTools: () => [], callTool: async () => ({ content: [] }) })).toBe(true);
    expect(isWinterMcpServerInstance({ listTools: () => [] })).toBe(false);
    expect(isWinterMcpServerInstance({ callTool: async () => ({ content: [] }) })).toBe(false);
    expect(isWinterMcpServerInstance(undefined)).toBe(false);
    expect(isWinterMcpServerInstance(null)).toBe(false);
    expect(isWinterMcpServerInstance("not an object")).toBe(false);
  });

  test("a conforming instance's callTool is directly invocable with (name, arguments) and returns a CallToolResult-shaped object -- the exact contract query.ts's makeSdkMcpCallHandler invokes and the runtime's own sdk_mcp_call executor expects back", async () => {
    const calls: Array<{ name: string; args: Record<string, unknown> }> = [];
    const instance: WinterMcpServerInstance = {
      listTools: () => [{ name: "echo", inputSchema: { type: "object" } }],
      async callTool(name, args) {
        calls.push({ name, args });
        return { content: [{ type: "text", text: `echo:${JSON.stringify(args)}` }] };
      },
    };
    expect(isWinterMcpServerInstance(instance)).toBe(true);
    const result = await instance.callTool("echo", { x: 1 });
    expect(calls).toEqual([{ name: "echo", args: { x: 1 } }]);
    expect(result).toEqual({ content: [{ type: "text", text: 'echo:{"x":1}' }] });
  });
});
