// Phase 6 Task 6 (Lane B): the R6-L enforcement point for HOST-SUPPLIED headers.
//
// `applyPrivilegedHeaders` (endpoint-policy.ts, FROZEN) gates the set an ADAPTER builds: on a
// non-generated policy it returns `{}`. What it cannot do is REMOVE a name from a header map it
// never saw — so a host that writes `x-goog-user-project` into `ConnectionProfile.headers` puts the
// operator's account topology on a user endpoint, straight past the rule, because the adapter's own
// set was empty and there was nothing to gate.
//
// R6-L stands as written and is strict: a user endpoint that legitimately needs an organisation
// header must be marked GENERATED by the host. So this helper is the other half of the same rule —
// the host's map goes through it before it is spread, and on a non-generated policy the
// identity-bearing names are dropped.
//
// WHICH NAMES. `endpoint-policy.ts` documents the split itself and this list is taken from it
// verbatim rather than re-derived: organisation / project / account identifiers, "any header whose
// value only means something at the reviewed endpoint it was minted for". A family that defines its
// own adds it through `extraPrivileged` — nothing here guesses on a family's behalf.
//
// AUTH IS DELIBERATELY NOT HERE, for the same reason `applyPrivilegedHeaders` excludes it: a
// credential has its own, stricter rule (`stripCredentialHeaders` on an origin change), and a user
// endpoint legitimately needs one to be reachable at all.
import type { EndpointPolicy } from "../endpoint-policy.ts";

/**
 * Header names that carry an ORGANISATION / PROJECT / ACCOUNT identity.
 *
 * Lowercase, because a raw record's keys are compared case-insensitively here (a `Headers` object
 * would do it for us; a plain object will not).
 */
export const PRIVILEGED_IDENTITY_HEADERS: readonly string[] = ["x-goog-user-project", "x-goog-quota-project", "openai-organization", "openai-project"];

/**
 * The host's own connection headers, filtered for the endpoint they are about to be sent to.
 *
 * IDENTITY on a generated endpoint (a reviewed descriptor endpoint vouches for the identity headers
 * that belong to it); on a user endpoint the privileged names are dropped and everything else is
 * kept — a host's proxy token, a tracing header, a `user-agent` are all its own business.
 *
 * Returns a COPY either way, so a `ConnectionProfile` reused across requests is never mutated.
 */
export function hostHeaders(policy: EndpointPolicy, headers: Record<string, string> | undefined, extraPrivileged: readonly string[] = []): Record<string, string> {
  if (headers === undefined) return {};
  if (policy.generated) return { ...headers };
  const blocked = new Set([...PRIVILEGED_IDENTITY_HEADERS, ...extraPrivileged].map((name) => name.toLowerCase()));
  const out: Record<string, string> = {};
  for (const [name, value] of Object.entries(headers)) {
    if (blocked.has(name.toLowerCase())) continue;
    out[name] = value;
  }
  return out;
}
