// Phase 6 Task 6 (Lane B): the R6-L enforcement point for HOST-SUPPLIED headers.
//
// `applyPrivilegedHeaders` (endpoint-policy.ts, FROZEN) gates the set an ADAPTER builds: on a
// non-generated policy it returns `{}`. What it cannot do is REMOVE a name from a header map it
// never saw — so a host that writes `x-goog-user-project` into `ConnectionProfile.headers` puts the
// operator's account topology on a user endpoint, straight past the rule, because the adapter's own
// set was empty and there was nothing to gate.
//
// R6-L stands as written and is strict: a user endpoint that legitimately needs an organisation
// header must be marked GENERATED by the host. So this helper is the other half of the same rule —
// the host's map goes through it before it is spread, and on a non-generated policy the
// identity-bearing names are dropped.
//
// WHICH NAMES. `endpoint-policy.ts` documents the split itself and this list is taken from it
// verbatim rather than re-derived: organisation / project / account identifiers, "any header whose
// value only means something at the reviewed endpoint it was minted for". A family that defines its
// own adds it through `extraPrivileged` — nothing here guesses on a family's behalf.
//
// CREDENTIAL-SHAPED NAMES ARE DROPPED UNCONDITIONALLY, on a generated endpoint as well (fix-wave
// ruling F-3, whole-branch review M-4). This is NOT the auth rule `applyPrivilegedHeaders` excludes
// -- an ADAPTER must be able to attach a credential to a user endpoint or nothing is reachable. It
// is the rule for the HOST's own map: a `ConnectionProfile` is non-secret connection metadata by
// contract (WS-13 §6), so a credential appearing in it is a misconfiguration to drop rather than a
// second auth channel to honour, whatever the endpoint's provenance.
//
// Before this, the three families read the rule two different ways: the OpenAI family stripped
// `CREDENTIAL_HEADER_NAMES` from the profile before calling this helper, and Anthropic/Google/Vertex
// did not -- so a host `cookie` or `proxy-authorization` rode every Anthropic and Google request,
// and Bedrock's own filter (which stays, for the SigV4 names it owns) missed the same three. Folding
// the strip in here is what makes "one filter every family goes through" true rather than aspirational.
import { CREDENTIAL_HEADER_NAMES, type EndpointPolicy } from "../endpoint-policy.ts";

/**
 * Header names that carry an ORGANISATION / PROJECT / ACCOUNT identity.
 *
 * Lowercase, because a raw record's keys are compared case-insensitively here (a `Headers` object
 * would do it for us; a plain object will not).
 */
export const PRIVILEGED_IDENTITY_HEADERS: readonly string[] = ["x-goog-user-project", "x-goog-quota-project", "openai-organization", "openai-project"];

/**
 * The host's own connection headers, filtered for the endpoint they are about to be sent to.
 *
 * TWO RULES, with deliberately different reach:
 *
 *   CREDENTIALS — every name on `CREDENTIAL_HEADER_NAMES` is dropped ALWAYS, generated endpoint or
 *     not. A profile is non-secret connection metadata by contract; a credential in it is a
 *     misconfiguration, and a reviewed endpoint does not make it less of one.
 *
 *   IDENTITY — the privileged names are dropped on a USER endpoint only; on a generated one a
 *     reviewed descriptor endpoint vouches for the identity headers that belong to it. (Three of the
 *     four privileged names are on the credential list too, so `x-goog-quota-project` is the only
 *     header where the two rules actually differ.)
 *
 * Everything else is kept on both — a host's proxy token, a tracing header, a `user-agent` are all
 * its own business.
 *
 * Returns a COPY either way, so a `ConnectionProfile` reused across requests is never mutated.
 */
export function hostHeaders(policy: EndpointPolicy, headers: Record<string, string> | undefined, extraPrivileged: readonly string[] = []): Record<string, string> {
  if (headers === undefined) return {};
  const blocked = new Set(
    (policy.generated ? CREDENTIAL_HEADER_NAMES : [...CREDENTIAL_HEADER_NAMES, ...PRIVILEGED_IDENTITY_HEADERS, ...extraPrivileged]).map((name) => name.toLowerCase()),
  );
  const out: Record<string, string> = {};
  for (const [name, value] of Object.entries(headers)) {
    if (blocked.has(name.toLowerCase())) continue;
    out[name] = value;
  }
  return out;
}
