// RULING R4-2 (2026-09-04-winter-phase-04-mcp-toolsearch-subagents.md): every seam Task 2/Task 3
// ships is accompanied by an executable contract test that BOTH consuming lanes keep green. This is
// P3's whole-branch lesson (a Critical and three Importants from producer/consumer drift) made
// structural for Phase 4.
//
// Lanes A/B: THIS FILE IS THE SEAM AUTHORITY -- keep it green; do not edit it. If your change makes
// one of these tests fail, your change is inconsistent with the seam contract this task pinned, not
// a reason to relax the assertion. (If the contract itself is genuinely wrong, that is a spine
// change -- raise it with the controller, do not edit this file from a lane worktree; R4-10's
// no-touch list names this file's owning task, not lane territory.)
//
// Scope note on (iii) "load-first": the ACTUAL execution-boundary enforcement (engine.ts rejecting a
// call to a deferred-and-unloaded tool with a typed error, never executing it) is Task 3's own
// wiring, not built here. This file proves the TWO INGREDIENTS that rule combines --
// `resolveDeferral(...) === "deferred"` and `LoadedToolSet.isLoaded(name) === false` -- transition
// correctly through registration/load/reset; Task 3's engine.test.ts is where the actual rejection
// behavior itself gets its own fixture.
//
// Producer/consumer coupling this file also documents (not itself testable without a real
// transport, but load-bearing for Lane A's own design): registerMcpServerTools's same-server
// REPLACE preserves an already-installed executor (registry.ts's own header). A per-tool executor
// Lane A installs via replaceExecutor therefore MUST NOT close over per-connection state (e.g. a
// specific transport client instance) that a reconnect would invalidate -- either read through a
// mutable slot, or re-call replaceExecutor after every reconnect. Getting this wrong reproduces
// exactly the P3 producer/consumer drift class R4-2 exists to catch, just one layer up (behavioral,
// not just typological).
import { describe, test, expect } from "bun:test";
import "./descriptors/index.ts";
import {
  registerMcpServerTools,
  unregisterMcpServerTools,
  onRegistryChange,
  getRegisteredTool,
  buildAdvertisedSet,
  createLoadedToolSet,
  resolveDeferral,
  type DeferralActivation,
} from "./registry.ts";
import { createFakeMcpServerStateSource } from "../mcp/state.ts";

// Distinct from registry.test.ts's own "t2regsrv" -- see registry.ts's own header on why the
// registry is a shared, process-wide singleton across every file in one `bun test` invocation.
const SRV = "t2seamsrv";

describe("(i) registry mutation <-> advertised set <-> change notification", () => {
  test("registering a live MCP server's tools fires onRegistryChange and makes the tool advertisable ONLY once winter.mcp is supplied", () => {
    let changeCount = 0;
    const unsubscribe = onRegistryChange(() => {
      changeCount++;
    });
    try {
      expect(buildAdvertisedSet({ mode: "default", capabilities: ["winter.mcp"] }).map((d) => d.canonicalName)).not.toContain(`mcp__${SRV}__foo`);

      registerMcpServerTools(SRV, [{ name: "foo", inputSchema: { type: "object" } }], { deferredDefault: false });
      expect(changeCount).toBe(1);
      expect(buildAdvertisedSet({ mode: "default" }).map((d) => d.canonicalName)).not.toContain(`mcp__${SRV}__foo`); // winter.mcp not supplied
      expect(buildAdvertisedSet({ mode: "default", capabilities: ["winter.mcp"] }).map((d) => d.canonicalName)).toContain(`mcp__${SRV}__foo`);

      unregisterMcpServerTools(SRV);
      expect(changeCount).toBe(2);
      expect(buildAdvertisedSet({ mode: "default", capabilities: ["winter.mcp"] }).map((d) => d.canonicalName)).not.toContain(`mcp__${SRV}__foo`);
    } finally {
      unsubscribe();
      unregisterMcpServerTools(SRV); // idempotent safety net
    }
  });
});

describe("(ii) McpServerStateSource semantics, proven against the fake (WS-09 §2.1/§8.4)", () => {
  test("a transition fires every subscriber with the fresh snapshot", () => {
    const source = createFakeMcpServerStateSource([{ name: "gh", state: "pending", toolNames: [] }]);
    const seen: string[] = [];
    source.subscribe((states) => seen.push(states.find((s) => s.name === "gh")!.state));
    source.transition("gh", "connected", { toolNames: ["list_issues"] });
    expect(seen).toEqual(["connected"]);
  });

  test("waitForPending resolves as soon as a transition clears the awaited server, before the deadline", async () => {
    const source = createFakeMcpServerStateSource([{ name: "gh", state: "pending", toolNames: [] }]);
    const promise = source.waitForPending(["gh"], 5000);
    setTimeout(() => source.transition("gh", "connected", { toolNames: ["list_issues"] }), 5);
    const started = Date.now();
    const result = await promise;
    expect(Date.now() - started).toBeLessThan(1000); // resolved on the transition, not the 5s deadline
    expect(result.find((s) => s.name === "gh")?.state).toBe("connected");
  });

  test("waitForPending resolves at the deadline when a server never leaves pending", async () => {
    const source = createFakeMcpServerStateSource([{ name: "stuck", state: "pending", toolNames: [] }]);
    const started = Date.now();
    const result = await source.waitForPending(["stuck"], 40);
    expect(Date.now() - started).toBeGreaterThanOrEqual(30);
    expect(result.find((s) => s.name === "stuck")?.state).toBe("pending");
  });

  test("`cached` counts as ready -- never blocks waitForPending (WS-09 §8.4)", async () => {
    const source = createFakeMcpServerStateSource([{ name: "cachedSrv", state: "cached", toolNames: ["cachedTool"] }]);
    const started = Date.now();
    const result = await source.waitForPending(["cachedSrv"], 5000);
    expect(Date.now() - started).toBeLessThan(1000); // did not wait out the 5s deadline
    expect(result.find((s) => s.name === "cachedSrv")?.state).toBe("cached");
  });
});

describe("(iii) deferral: load-first (WS-09 §8.5 execution-boundary ingredients)", () => {
  const activeToolSearch: DeferralActivation = { enableToolSearch: "true", providerSupportsToolSearch: true, deferrableContextShare: 100 };

  test("a deferred, unloaded name is NOT callable-eligible; load() makes it eligible; reset(evidenced) re-hides it", () => {
    try {
      registerMcpServerTools(SRV, [{ name: "search_docs", inputSchema: { type: "object" } }], { deferredDefault: true });
      const canonicalName = `mcp__${SRV}__search_docs`;
      const descriptor = getRegisteredTool(canonicalName)!.descriptor;

      // Ingredient 1: this descriptor IS resolved as deferred under active Tool Search.
      expect(resolveDeferral(descriptor, "default", activeToolSearch)).toBe("deferred");

      const loadedSet = createLoadedToolSet();
      // Ingredient 2, before load(): NOT in the loaded set -- combined with ingredient 1, this is
      // exactly the pair Task 3's execution-boundary rule rejects a call against (never executed).
      expect(loadedSet.isLoaded(canonicalName)).toBe(false);

      // ToolSearch "loads" it (WS-09 §8.2's own successful-selection consequence).
      const { loaded, unknown } = loadedSet.load([canonicalName]);
      expect(loaded).toEqual([canonicalName]);
      expect(unknown).toEqual([]);
      expect(loadedSet.isLoaded(canonicalName)).toBe(true); // now callable-eligible

      // Compaction removes the discovery history that introduced it (WS-09 §8.5 "Compaction
      // reset") -- the re-derived evidenced set no longer includes this name.
      loadedSet.reset([]);
      expect(loadedSet.isLoaded(canonicalName)).toBe(false); // re-hidden: back to load-first
    } finally {
      unregisterMcpServerTools(SRV);
    }
  });

  test("reset(evidenced) is a re-derivation, not a wipe: a name that remained evidenced survives", () => {
    const loadedSet = createLoadedToolSet();
    loadedSet.load(["Read", "Edit"]);
    loadedSet.reset(["Read"]); // "Edit" fell out of the surviving transcript; "Read" remained evidenced
    expect(loadedSet.isLoaded("Read")).toBe(true);
    expect(loadedSet.isLoaded("Edit")).toBe(false);
  });
});

describe("(iv) _meta preservation round-trip (WS-09 §6)", () => {
  test("_meta round-trips VERBATIM including the anthropic/ key literal, and derives descriptor.interaction", () => {
    try {
      registerMcpServerTools(
        SRV,
        [
          {
            name: "delete_repo",
            inputSchema: { type: "object" },
            _meta: { "anthropic/requiresUserInteraction": true, "some-server/custom-key": 42 },
          },
        ],
        { deferredDefault: false },
      );
      const descriptor = getRegisteredTool(`mcp__${SRV}__delete_repo`)!.descriptor;
      // Verbatim: the EXACT object, including a key this task assigns no meaning to at all.
      expect(descriptor._meta).toEqual({ "anthropic/requiresUserInteraction": true, "some-server/custom-key": 42 });
      expect(descriptor.interaction).toBe("required");
    } finally {
      unregisterMcpServerTools(SRV);
    }
  });

  test("a sibling _meta key alone (no anthropic/requiresUserInteraction) round-trips but does NOT set interaction", () => {
    try {
      registerMcpServerTools(SRV, [{ name: "list_repos", inputSchema: { type: "object" }, _meta: { "anthropic/alwaysLoad": true } }], {
        deferredDefault: false,
      });
      const descriptor = getRegisteredTool(`mcp__${SRV}__list_repos`)!.descriptor;
      expect(descriptor._meta).toEqual({ "anthropic/alwaysLoad": true });
      expect(descriptor.interaction).toBeUndefined();
    } finally {
      unregisterMcpServerTools(SRV);
    }
  });

  test("requiresUserInteraction must be the exact boolean true -- a truthy-but-not-true value does NOT set interaction", () => {
    try {
      registerMcpServerTools(SRV, [{ name: "truthy_case", inputSchema: { type: "object" }, _meta: { "anthropic/requiresUserInteraction": "yes" } }], {
        deferredDefault: false,
      });
      const descriptor = getRegisteredTool(`mcp__${SRV}__truthy_case`)!.descriptor;
      expect(descriptor._meta).toEqual({ "anthropic/requiresUserInteraction": "yes" }); // preserved verbatim regardless
      expect(descriptor.interaction).toBeUndefined(); // but NOT derived -- exact === true only
    } finally {
      unregisterMcpServerTools(SRV);
    }
  });
});
